apiVersion: v1
kind: Service
metadata:
  name:  kishor-app-service
  namespace: kishor
spec:
  type: NodePort
  selector:
    app: kishor-app
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000